### ISSUE TITLE
deploy.aws.test.test_ecs.CommandLineTests.test_environment_set failed in CI

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-deploy#15]
Except from [build log](https://travis-ci.com/burningmantech/ranger-deploy/jobs/188946364):

```console
Falsifying example: test_environment_set(self=<deploy.aws.test.test_ecs.CommandLineTests testMethod=test_environment_set>, cluster='0', service='0', updates=[('=', '')])
You can reproduce this example by temporarily adding @reproduce_failure('4.14.0', b'AAEAAAABAAAAAQEBAAANAAAA') as a decorator on your test case
```

```console
[FAIL]
Traceback (most recent call last):
  File "/home/travis/build/burningmantech/ranger-deploy/.tox/coverage-py37/lib/python3.7/site-packages/deploy/aws/test/test_ecs.py", line 1109, in test_environment_set
    text(min_size=1), text(min_size=1),
  File "/home/travis/build/burningmantech/ranger-deploy/.tox/coverage-py37/lib/python3.7/site-packages/hypothesis/core.py", line 1017, in wrapped_test
    raise the_error_hypothesis_found
  File "/home/travis/build/burningmantech/ranger-deploy/.tox/coverage-py37/lib/python3.7/site-packages/deploy/aws/test/test_ecs.py", line 1145, in test_environment_set
    (f"    Setting x{k}.", {}) for k, v in updates
  File "/home/travis/build/burningmantech/ranger-deploy/.tox/coverage-py37/lib/python3.7/site-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/opt/python/3.7.1/lib/python3.7/unittest/case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/python/3.7.1/lib/python3.7/unittest/case.py", line 1045, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/opt/python/3.7.1/lib/python3.7/unittest/case.py", line 1027, in assertSequenceEqual
    self.fail(msg)
twisted.trial.unittest.FailTest: Lists differ: [('Changing environment variables for 0:0:', {}), ('    Setting x.', {})] != [('Changing environment variables for 0:0:', {}), ('    Setting x=.', {})]
First differing element 1:
('    Setting x.', {})
('    Setting x=.', {})
- [('Changing environment variables for 0:0:', {}), ('    Setting x.', {})]
+ [('Changing environment variables for 0:0:', {}), ('    Setting x=.', {})]
?                                                                  +
```

**Comment by wsanchez** [comment]
The key here is `=`, which is special.

**Comment by wsanchez** [comment]
Fixes applies in a few PRs. Seems OK now.
